### ISSUE TITLE
下载你的gradle自定义插件失败

### ISSUE THREAD

**Issue by df13954** [5A59/android-training#8]
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'EasyGradle'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.zy.plugin:myplugin:0.0.1.
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.pom
         https://dl.google.com/dl/android/maven2/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.jar
         https://jcenter.bintray.com/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.pom
         https://jcenter.bintray.com/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.jar
         file:/Users/os/.m2/repository/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.pom
         file:/Users/os/.m2/repository/com/zy/plugin/myplugin/0.0.1/myplugin-0.0.1.jar
     Required by:
         project :`
gradle分析那个项目，初始化的时候失败了，我应该怎么解决呢

**Comment by Omooo** [comment]
先把 plugin 注释掉，然后在 ./gradlew uploadArchives 就好了。

**Comment by df13954** [comment]
感谢
